Window.SetBackgroundTopColor(0.01, 0.07, 0.14);
Window.SetBackgroundBottomColor(0.00, 0.02, 0.06);
logo = Image("mi-linux-boot-splash.png");
sprite = Sprite(logo);
sprite.SetX(Window.GetWidth() / 2 - logo.GetWidth() / 2);
sprite.SetY(Window.GetHeight() / 2 - logo.GetHeight() / 2);
message_sprite = Sprite();
fun refresh_callback() {
    sprite.SetX(Window.GetWidth() / 2 - logo.GetWidth() / 2);
    sprite.SetY(Window.GetHeight() / 2 - logo.GetHeight() / 2);
}
Plymouth.SetRefreshFunction(refresh_callback);
