---
dontChroot: false
timeout: 10
script:
  - command: "if [ -f /usr/share/applications/calamares.desktop.orig ] && [ -f /usr/share/applications/calamares.desktop ]; then cp -f /usr/share/applications/calamares.desktop /usr/share/applications/calamares.desktop.orig; fi"
    timeout: 10
