---
dontChroot: false
timeout: 10
script:
  - command: "if [ -f /usr/share/applications/calamares.desktop.orig ] && [ -f /usr/share/applications/calamares.desktop ]; then rm -f /usr/share/applications/calamares.desktop; fi"
    timeout: 10
